/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

/**
 *
 * @author Bekhzod
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private Bank bank;
    private Customer customer;
    private Clerk clerk;
    
    public LoginForm() {
            initComponents();
            setLocationRelativeTo(null);
            warningText.setVisible(false);
            buttonGroup1.add(clerkRadioButton);
            buttonGroup1.add(customerRadioButton);
        
            customer = null;
            bank = new Bank();
        
            Account account1 = new Savings(250);
            Account account2 = new Checking(530.50);
            Account account3 = new Credit(2000);
            Account account4 = new Checking(450);
            Account account5 = new Savings(226);
            Account account6 = new Credit(1200);
            Account account7 = new Savings(300);

            Customer customer1 = new Customer("Bekhzod", "Turdialiev", "123456789", account1);
            Customer customer2 = new Customer("Bernardy", "Ho", "123456780", account2);
            Customer customer3 = new Customer("Valetta", "Jesslyn", "123456781", account3);
            Customer customer4 = new Customer("Aziz", "Davronov", "123456782", account4);
            Customer customer5 = new Customer("Shaxzod", "Turdialiev", "123456783", account5);
            Customer customer6 = new Customer("Abdulla", "Al Jabeer", "123456783", account6);
            Customer customer7 = new Customer("John", "Tumaini", "123453783", account7);
            
            clerk = new Clerk("Someone", "Anyone");

            bank.addCustomer(customer1);
            bank.addCustomer(customer2);
            bank.addCustomer(customer3);
            bank.addCustomer(customer4);
            bank.addCustomer(customer5);
            bank.addCustomer(customer6);
            bank.addCustomer(customer7);
            
    }
    
    public LoginForm(Bank bank) {
        initComponents();
        setLocationRelativeTo(null);
        buttonGroup1.add(clerkRadioButton);
        buttonGroup1.add(customerRadioButton);
        
        customer = null;
        
        
        this.bank = bank;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        passwordText = new javax.swing.JLabel();
        accountIdText = new javax.swing.JLabel();
        accountIdLabel = new javax.swing.JTextField();
        clerkRadioButton = new javax.swing.JRadioButton();
        customerRadioButton = new javax.swing.JRadioButton();
        resetButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        warningText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));

        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 51));

        passwordText.setForeground(new java.awt.Color(255, 255, 255));
        passwordText.setText("Password");

        accountIdText.setForeground(new java.awt.Color(255, 255, 255));
        accountIdText.setText("Clerk ID");

        accountIdLabel.setText("100000");

        clerkRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        clerkRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        clerkRadioButton.setSelected(true);
        clerkRadioButton.setText("Clerk");
        clerkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkRadioButtonActionPerformed(evt);
            }
        });

        customerRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        customerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        customerRadioButton.setText("Customer");
        customerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRadioButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.setText("abc123456");

        warningText.setForeground(new java.awt.Color(255, 255, 255));
        warningText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jDesktopPane1.setLayer(passwordText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(accountIdText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(accountIdLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clerkRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(customerRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(resetButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(loginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(warningText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(customerRadioButton)
                        .addGap(79, 79, 79)
                        .addComponent(clerkRadioButton))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(accountIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(accountIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(130, 130, 130))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(warningText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerRadioButton)
                    .addComponent(clerkRadioButton))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        accountIdLabel.setText("100000");
        passwordField.setText("abc123456");
        clerkRadioButton.setSelected(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(accountIdLabel.getText().trim().equals("")) {
            warningText.setVisible(true);
            warningText.setText("Account ID is empty! Please, fill and try again.");
        }
        else if(!accountIdLabel.getText().matches("[0-9]{6}")) {
            warningText.setVisible(true);
            warningText.setText("Account ID must be 6 numbers!");
        }
        else if(String.valueOf(passwordField.getPassword()).trim().equals("")) {
            warningText.setVisible(true);
            warningText.setText("Password is empty! Please, fill and try again.");
        }
        else {
            if(clerkRadioButton.isSelected()) {
                if(accountIdLabel.getText().equals("100000") && String.valueOf(passwordField.getPassword()).equals("bcd321654")) {
                    MainMenuClerk menuClerk = new MainMenuClerk(bank);
                    menuClerk.setVisible(true);
                    this.dispose();
                }
                else{
                    warningText.setVisible(true);
                    warningText.setText("Clerk ID or Password is incorrect");
                }
            }
            else if(customerRadioButton.isSelected()) {
                int accountNumber = Integer.parseInt(accountIdLabel.getText());
                if(bank.accountExists(accountNumber)){
                    customer = bank.getCustomerByAccountNumber(accountNumber);
                    if(customer.getAccount().checkPassword(String.valueOf(passwordField.getPassword()))) {
                        MainMenuCustomer menuCustomer = new MainMenuCustomer(bank, customer);
                        menuCustomer.setVisible(true);
                        this.dispose();
                    }
                    else{
                        warningText.setVisible(true);
                        warningText.setText("Account ID or Password is incorrect");
                    }

                }
                else{
                    warningText.setVisible(true);
                    warningText.setText("Account not found");
                }           
            }     
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void clerkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkRadioButtonActionPerformed
        accountIdText.setText("Clerk ID");
    }//GEN-LAST:event_clerkRadioButtonActionPerformed

    private void customerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRadioButtonActionPerformed
        accountIdText.setText("Account ID");
    }//GEN-LAST:event_customerRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountIdLabel;
    private javax.swing.JLabel accountIdText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clerkRadioButton;
    private javax.swing.JRadioButton customerRadioButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel warningText;
    // End of variables declaration//GEN-END:variables
}
