/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import com.sun.corba.se.impl.io.IIOPOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bekhzod
 */
public class MainMenuCustomer extends javax.swing.JFrame {

    private Bank bank;
    private Customer customer;

    private String saveLocation = null;

    /**
     * Creates new form MainMenu
     */
    public MainMenuCustomer(Bank bank, Customer customer) {
        initComponents();
        setLocationRelativeTo(null);
        this.bank = bank;
        this.customer = customer;
        alertText.setText("Welcome back, " + customer.getLastName());
        accountIdField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
        nameField.setText(customer.getFirstName() + " " + customer.getLastName());
        accountTypeField.setText(customer.getAccount().getAccountType());
        balanceField.setText(String.valueOf(customer.getAccount().getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new javax.swing.JPanel();
        depositButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        withdrawButton1 = new javax.swing.JButton();
        accountIdText = new javax.swing.JLabel();
        accountIdField = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        accountTypeText = new javax.swing.JLabel();
        accountTypeField = new javax.swing.JTextField();
        balanceField = new javax.swing.JTextField();
        balanceText = new javax.swing.JLabel();
        reLoginButton = new javax.swing.JButton();
        alertText = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        reLoginMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Application (Customer)");
        setMinimumSize(new java.awt.Dimension(550, 400));

        ContentPanel.setMinimumSize(new java.awt.Dimension(530, 120));
        ContentPanel.setPreferredSize(new java.awt.Dimension(530, 400));

        depositButton.setText("Deposit");
        depositButton.setMaximumSize(new java.awt.Dimension(111, 23));
        depositButton.setMinimumSize(new java.awt.Dimension(111, 23));
        depositButton.setPreferredSize(new java.awt.Dimension(111, 23));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        transferButton.setText("Transfer");
        transferButton.setMaximumSize(new java.awt.Dimension(111, 23));
        transferButton.setMinimumSize(new java.awt.Dimension(111, 23));
        transferButton.setPreferredSize(new java.awt.Dimension(111, 23));
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        withdrawButton1.setText("Withdrawal");
        withdrawButton1.setMaximumSize(new java.awt.Dimension(111, 23));
        withdrawButton1.setMinimumSize(new java.awt.Dimension(111, 23));
        withdrawButton1.setPreferredSize(new java.awt.Dimension(111, 23));
        withdrawButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButton1ActionPerformed(evt);
            }
        });

        accountIdText.setText("Account ID");

        accountIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountIdFieldFocusLost(evt);
            }
        });
        accountIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountIdFieldActionPerformed(evt);
            }
        });
        accountIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accountIdFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountIdFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountIdFieldKeyTyped(evt);
            }
        });

        nameText.setText("Name");

        accountTypeText.setText("Account Type");

        balanceText.setText("Balance");

        reLoginButton.setText("Re-Login");
        reLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reLoginButtonActionPerformed(evt);
            }
        });

        alertText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(withdrawButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(alertText, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(accountIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(accountTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(accountTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(reLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(alertText)
                .addGap(30, 30, 30)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(reLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FileMenu.setText("File");

        reLoginMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reLoginMenuItem.setText("Re-login");
        reLoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reLoginMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(reLoginMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-16.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenuItem);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        if (customer != null) {
            DepositMenu menu = new DepositMenu(this, true, customer);
            menu.setVisible(true);
            reloadBalance();
        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        if (customer != null) {
            TransferMenu menu = new TransferMenu(this, true, customer, bank);
            menu.setVisible(true);
            reloadBalance();
        }
    }//GEN-LAST:event_transferButtonActionPerformed

    private void withdrawButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButton1ActionPerformed
        if (customer != null) {
            WithdrawalMenu menu = new WithdrawalMenu(this, true, customer);
            menu.setVisible(true);
            reloadBalance();
        }
    }//GEN-LAST:event_withdrawButton1ActionPerformed

    private void accountIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountIdFieldActionPerformed

    private void reLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reLoginButtonActionPerformed
        LoginForm loginForm = new LoginForm(bank);
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reLoginButtonActionPerformed

    private void accountIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountIdFieldFocusLost
        accountIdField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
        //customer.getFirstName()+" "+customer.getLastName()
    }//GEN-LAST:event_accountIdFieldFocusLost

    private void accountIdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountIdFieldKeyTyped
        accountIdField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
    }//GEN-LAST:event_accountIdFieldKeyTyped

    private void accountIdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountIdFieldKeyPressed
        accountIdField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
    }//GEN-LAST:event_accountIdFieldKeyPressed

    private void accountIdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountIdFieldKeyReleased
        accountIdField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
    }//GEN-LAST:event_accountIdFieldKeyReleased

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void reLoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reLoginMenuItemActionPerformed
        LoginForm loginForm = new LoginForm(bank);
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reLoginMenuItemActionPerformed

    private boolean saveFile(String fileName) {
        try {
            FileOutputStream fOut = new FileOutputStream(fileName);
            ObjectOutputStream objOut = new ObjectOutputStream(fOut);
            objOut.writeObject(bank);
            objOut.close();
            fOut.close();
            return true;
        } catch (FileNotFoundException ex) {
            return false;
        } catch (IOException ex) {
            return false;
        }
    }


    private void reloadBalance() {
        balanceField.setText(String.valueOf(bank.round(customer.getAccount().getBalance(), 2)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField accountIdField;
    private javax.swing.JLabel accountIdText;
    private javax.swing.JTextField accountTypeField;
    private javax.swing.JLabel accountTypeText;
    private javax.swing.JLabel alertText;
    private javax.swing.JTextField balanceField;
    private javax.swing.JLabel balanceText;
    private javax.swing.JButton depositButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameText;
    private javax.swing.JButton reLoginButton;
    private javax.swing.JMenuItem reLoginMenuItem;
    private javax.swing.JButton transferButton;
    private javax.swing.JButton withdrawButton1;
    // End of variables declaration//GEN-END:variables

    

}
