/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import com.sun.corba.se.impl.io.IIOPOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

/**
 *
 * @author Bekhzod
 */
public class Statistics extends javax.swing.JFrame {

    private Bank bank;

    private String saveLocation = null;

    /**
     * Creates new form MainMenu
     */
    
    public Statistics(Bank bank) {
        initComponents();
        
        setLocationRelativeTo(null);
        this.bank = bank;
        
        
        //System.out.println(bank.getCustomers());
    }

    private void initStats() {
        accNumberField.setText(String.valueOf(accNumber()));
        totalBalanceField.setText(String.valueOf(totalBalance()));
        avgBalanceField.setText(String.valueOf(avgBalance()));
        savingsNumberField.setText(String.valueOf(accountTypesNumber("Savings")));
        checkingNumberField.setText(String.valueOf(accountTypesNumber("Checking")));
        creditNumberField.setText(String.valueOf(accountTypesNumber("Credit")));
        allDepositField.setText(String.valueOf(totalBalanceByType("Deposit")));
        allCreditField.setText(String.valueOf(totalBalanceByType("Credit")));
        avgDepositField.setText(String.valueOf(avgDeposit()));
    }
    
    private int accNumber() {
        return bank.getCustomers().size();
    }
    
    private double totalBalance() {
        int totalBalance = 0;
        for(Customer c : bank.getCustomers()) {
            totalBalance += c.getAccount().getBalance();
        }
        return totalBalance;
    }
    
    private double avgBalance() {
        return bank.round(totalBalance()/accNumber(), 2);
    }
    
    private int accountTypesNumber(String type) {
        int count = 0;
        for(Customer c : bank.getCustomers()) {
            if(c.getAccount().getAccountType().equals(type)) {
                count++;
            }
        }
        return count;
    }
    
    private double totalBalanceByType(String type) {
        double total = 0;
        if(type.equals("Deposit")) {
            for(Customer c : bank.getCustomers()) {
                if(c.getAccount().getAccountType().equals("Checking") || c.getAccount().getAccountType().equals("Savings")) {
                    total += c.getAccount().getBalance();
                }
            }
        }
        else if(type.equals("Credit")) {
            for(Customer c : bank.getCustomers()) {
                if(c.getAccount().getAccountType().equals("Credit")) {
                    total += c.getAccount().getBalance();
                }
            }
        }
        return bank.round(total, 2);
    }
    
    private double avgDeposit() {
        int totalAmount = 0;
        int totalNumber = 1;
        for(Customer c : bank.getCustomers()) {
            if(!c.getAccount().getAccountType().equals("Credit")) {
                totalAmount += c.getAccount().getBalance();
                totalNumber++;
            }
        }
        return bank.round(totalAmount/totalNumber, 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        savingsNumberField = new javax.swing.JTextField();
        savingsNumberText = new javax.swing.JLabel();
        checkingNumberField = new javax.swing.JTextField();
        checkingNumberText = new javax.swing.JLabel();
        creditNumberField = new javax.swing.JTextField();
        creditNumberText = new javax.swing.JLabel();
        allDepositText = new javax.swing.JLabel();
        allDepositField = new javax.swing.JTextField();
        allCreditField = new javax.swing.JTextField();
        allCreditText = new javax.swing.JLabel();
        avgDepositField = new javax.swing.JTextField();
        avgDepositText = new javax.swing.JLabel();
        avgCreditText = new javax.swing.JLabel();
        avgCreditField = new javax.swing.JTextField();
        accNumberText = new javax.swing.JLabel();
        accNumberField = new javax.swing.JTextField();
        totalBalanceText = new javax.swing.JLabel();
        totalBalanceField = new javax.swing.JTextField();
        avgBalanceText = new javax.swing.JLabel();
        avgBalanceField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        statButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        reLoginMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Application (Clerk)");
        setMinimumSize(new java.awt.Dimension(550, 400));

        savingsNumberField.setText("0");
        savingsNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        savingsNumberField.setEnabled(false);

        savingsNumberText.setText("Saving Accounts");

        checkingNumberField.setText("0");
        checkingNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        checkingNumberField.setEnabled(false);

        checkingNumberText.setText("Checking Accounts");

        creditNumberField.setText("0");
        creditNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        creditNumberField.setEnabled(false);

        creditNumberText.setText("Credit Accounts");

        allDepositText.setText("All Deposit");

        allDepositField.setText("0");
        allDepositField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        allDepositField.setEnabled(false);

        allCreditField.setText("0");
        allCreditField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        allCreditField.setEnabled(false);

        allCreditText.setText("All Credit");

        avgDepositField.setText("0");
        avgDepositField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        avgDepositField.setEnabled(false);

        avgDepositText.setText("Average Deposit");

        avgCreditText.setText("Average Credit");

        avgCreditField.setText("0");
        avgCreditField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        avgCreditField.setEnabled(false);

        accNumberText.setText("Account Number");

        accNumberField.setText("0");
        accNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        accNumberField.setEnabled(false);

        totalBalanceText.setText("All Balance");

        totalBalanceField.setText("0");
        totalBalanceField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalBalanceField.setEnabled(false);

        avgBalanceText.setText("Average Balance");

        avgBalanceField.setText("0");
        avgBalanceField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        avgBalanceField.setEnabled(false);
        avgBalanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgBalanceFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(avgBalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avgBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(accNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(totalBalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savingsNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(savingsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkingNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(creditNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(creditNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(avgDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avgDepositField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(avgCreditText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avgCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(allDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allDepositField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(allCreditText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgBalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(savingsNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkingNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(allDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allDepositField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allCreditText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgDepositField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgCreditText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        statButton.setText("Statistics");
        statButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        reLoginMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reLoginMenuItem.setText("Re-login");
        reLoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reLoginMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(reLoginMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-16.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenuItem);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(statButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(statButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void reLoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reLoginMenuItemActionPerformed
        LoginForm loginForm = new LoginForm(bank);
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reLoginMenuItemActionPerformed

    private void avgBalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgBalanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgBalanceFieldActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        MainMenuClerk menuClerk = new MainMenuClerk(bank);
                menuClerk.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void statButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButtonActionPerformed
        initStats();
    }//GEN-LAST:event_statButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        for(Customer c : bank.getCustomers()) {
            if(!c.getAccount().getAccountType().equals("Credit")) {
                c.getAccount().update();
            }
        }
        initStats();
    }//GEN-LAST:event_updateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField accNumberField;
    private javax.swing.JLabel accNumberText;
    private javax.swing.JTextField allCreditField;
    private javax.swing.JLabel allCreditText;
    private javax.swing.JTextField allDepositField;
    private javax.swing.JLabel allDepositText;
    private javax.swing.JTextField avgBalanceField;
    private javax.swing.JLabel avgBalanceText;
    private javax.swing.JTextField avgCreditField;
    private javax.swing.JLabel avgCreditText;
    private javax.swing.JTextField avgDepositField;
    private javax.swing.JLabel avgDepositText;
    private javax.swing.JTextField checkingNumberField;
    private javax.swing.JLabel checkingNumberText;
    private javax.swing.JTextField creditNumberField;
    private javax.swing.JLabel creditNumberText;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem reLoginMenuItem;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField savingsNumberField;
    private javax.swing.JLabel savingsNumberText;
    private javax.swing.JButton statButton;
    private javax.swing.JTextField totalBalanceField;
    private javax.swing.JLabel totalBalanceText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
